# Site settings
title: Teaching an Old Cat new tricks
header-img: img/home-bg.png
email: cannenorris@yahoo.com
copyright_name: wolfieandbetty
description: > # this means to ignore newlines until "baseurl:"
  Re-discovering purpose and passion
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  wolfieandbetty
learn_profile: wolfieandbetty
email_username: cannenorris@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
